Vagrant.configure(2) do |config|
    config.vm.box = "debian/buster64"
    config.vm.define "wiki" do |wiki|
       wiki.vm.network "private_network", ip: "192.168.96.10"
       wiki.vm.hostname = "wiki"
    end
    config.vm.define "backup" do |backup|
	backup.vm.box = "debian/buster64"
	backup.vm.network "private_network", ip: "192.168.96.32"
	backup.vm.hostname = "backup"
    end
    config.vm.provision "init", type: "shell", inline: <<-SHELL
	apt-get update
	apt-get upgrade
	apt-get install rsync -y
	echo "### Serveur apache installation..."
	apt-get -y install apache2
	echo "### Apache is installed"
	echo "### Démarrage automatique du serveur web"
	systemctl enable apache2.service
	echo "### Redémarrage d'apache"
	systemctl restart apache2.service
	echo "### SSH"
	cat ~/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
	echo "### Installation Dokuwiki..."
	sudo wget https://download.dokuwiki.org/out/dokuwiki-63487079d8919ad20087d39beea025a9.tgz
	sudo tar -xvf dokuwiki-63487079d8919ad20087d39beea025a9.tgz
	sudo rm -r dokuwiki-63487079d8919ad20087d39beea025a9.tgz
	echo "### Configuration serveur web"
	echo "<Server Hostname: wiki.lab.local>"	
    SHELL
end
