Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.box_check_update = false

  config.vm.provision "init", type: "shell", inlin$
    sudo apt install -y -qq apache2 libapache2-mod$
    useradd -m -G www-data wiki
    sudo mkdir /opt/src
    cd /opt/src
    sudo wget -q https://download.dokuwiki.org/out$
    sudo tar zxf dokuwiki-8a269cc015a64b40e4c91869$
    sudo rm /var/www/html/index.html
    cd /var/www/html/dokuwiki
    sudo mv * ../
    sudo chown -R wiki:www-data /var/www/html/
    sudo chmod -R g+w /var/www/html/
    mkdir /home/wiki/.ssh
    chmod 700 /home/wiki/.ssh
    cp /vagrant/id_rsa /home/wiki/.ssh
    cat /vagrant/id_rsa.pub > /home/wiki/.ssh/auth$
    ssh-keyscan 192.168.12.12 > /home/wiki/.ssh/kn$
    ssh-keyscan 192.168.12.13 >> /home/wiki/.ssh/k$
    chown -R wiki:wiki /home/wiki/.ssh
    chmod 600 /home/wiki/.ssh
    mkdir /var/www/html/public && touch /var/www/html/public/index.html
    echo "Site inconnu" > /var/www/html/public/index.html
    chown -R wiki:www-data /var/www/html/public
    cp /vagrant/wiki-lab.conf /etc/apache2/sites-available/
    a2ensite wiki-lab.conf && a2dissite 000-default.conf
    systemctl reload apache2.service 
  SHELL

  config.vm.define "master" do |master|
    master.vm.hostname = "wiki"
    master.vm.network "private_network", ip: "192.$
  end

  config.vm.define "backup" do |backup|
    backup.vm.hostname = "backup"
    backup.vm.network "private_network", ip: "192.$
    backup.vm.provision "cron", type: "shell", run$
      inline: <<-EOF
        echo should do rsync cron
        echo '*/5 * * * * rsync -avp --chown=wiki:$
      EOF
  end

  config.vm.define "proxy" do |proxy|
    proxy.vm.hostname = "proxy"
    proxy.vm.network "private_network", ip: "192.168.12.11"
    proxy.vm.provision "init", type: "shell", run: "once",
      inline: <<-EOF
        apt-get install nginx -y
      EOF
  end
end

